apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: default
data:
 redis.txt: |
  save 300 30
  rdbchecksum yes
  dbfilename redis_dump.rdb
  dir /data/redis/
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config-luigi
  namespace: default
data:
  GOOGLE_APPLICATION_CREDENTIALS: "/etc/gcs/gcs_key.json"
  GCP_FIRESTORE_SECRETS_PATH: "/etc/gcpfirestore/gcpfirestore_key.json"
  TELEGRAM_KEY_PATH: "/etc/telegram/telegram_key.json"
  LUIGI_BUCKET: 'gs://flats_jsonlines2'
  LUIGI_LOCALDIR: '/app/data/'
  LUIGI_BUCKET_PLOTS: 'gs://plots_jsonlines2'
  LUIGI_LOCALDIR_PLOTS: '/app/data_plots/'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
  namespace: default
data:
  GCP_FIRESTORE_SECRETS_PATH: "/etc/gcpfirestore/gcpfirestore_key.json"
  TELEGRAM_KEY_PATH: "/etc/telegram/telegram_key.json"
  TELEGRAM_FLATS_KEYWORDS: "x"
  TELEGRAM_FLATS_QUERY: "x"
  TELEGRAM_PLOTS_KEYWORDS: "rzek.|brzeg|jeziorem|jezioro|jeziorami|zalew|narew|narwi|bug|zegrz"
  TELEGRAM_PLOTS_QUERY: "distance <150 and price <130000"
  JSONLINE_FILE_DIR: "/app/data/"
  JSONLINE_ADDDATE2NAME: "True"
  REDIS_HOST: "localhost"
  REDIS_PORT: "6379"
  SCRAPER_DELAY_AFTER_EACH_RUN_SEC: "900"
  SCRAPER_START_DELAY_SEC: "30"
  SCRAPER_CONCURRENT_REQUESTS: "1"
  scr_pipe_ProcessItem: "100"
  scr_pipe_CheckIfExistRedis: "110"
  scr_pipe_CheckIfExistGCPFirestore: "120"
  scr_pipe_UpdateExistRedis: "125"
  scr_pipe_OutputFilter: "130"
  scr_pipe_ProcessItemGeocode: "140"
  scr_pipe_ValidSchema: "150"
  scr_pipe_OrderbySchema: "160"
  scr_pipe_SendTelegramMessage: "165"
  scr_pipe_OutputLocal: "170"
  scr_pipe_OutputGCPFirestore: "180"
  scr_pipe_OutputRedis: "190"
  scr_pipe_OutputStdout: "None"
