apiVersion: apps/v1
kind: Deployment
metadata:
  name: xflats
  labels:
    app: xflats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xflats
  template:
    metadata:
      labels:
        app: xflats
    spec:
      containers:
      - name: scraper
        image: xszpo/flat_scraper:1.0.3
        env:
        - name: SCRAPER_CRAWLER_NAME
          value: 'otodom, gratka, morizon'
        - name: JSONLINE_FILE_NAME
          value: 'flats_all'
        - name: SCRAPER_CRAWL_LIST_PAGES
          value: '2'
        envFrom:
          - configMapRef:
              name: env-config
        volumeMounts:
        - name: gcpfirestore
          mountPath: "/etc/gcpfirestore"
          readOnly: true
        - name: pv-volume-scraper-storage
          mountPath: "/app/data/"
        resources:
          limits:
            cpu: "0m"
            memory: "256Mi"
      - name: luigi
        image: xszpo/flats_luigi:0.0.1
        env:
        - name: LUIGI_DAYSBACK
          value: '12'
        - name: LUIGI_BUCKET
          value: 'gs://flats_jsonlines'
        - name: LUIGI_LOCALDIR
          value: '/app/data/'
        volumeMounts:
        - name: gcs
          mountPath: "/etc/gcs"
          readOnly: true
        - name: pv-volume-scraper-storage
          mountPath: "/app/data/"
        resources:
          limits:
            cpu: "100m"
            memory: "256Mi"
      - name: redis
        image: redis:5.0.8
        command:
          - redis-server
          - "/redis-master/redis.conf"
        env:
        - name: MASTER
          value: "true"
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "200m"
            memory: "512Mi"
            ephemeral-storage: "512M"
        volumeMounts:
        - name: pv-volume-redis-storage
          mountPath: /data/redis
        - name: config
          mountPath: /redis-master
      volumes:
      - name: gcpfirestore
        secret:
          secretName: gcp-firestore-dm7t9h22dh
      - name: gcs
        secret:
            secretName: gcp-gcs-m45tkfcf8m
      - name: pv-volume-scraper-storage
        persistentVolumeClaim:
          claimName: pv-local-scraper-claim
      - name: pv-volume-redis-storage
        persistentVolumeClaim:
          claimName: pv-local-redis-claim
      - name: config
        configMap:
          name: redis-config
          items:
          - key: redis.txt
            path: redis.conf