apiVersion: apps/v1
kind: Deployment
metadata:
  name: xflats
  labels:
    app: xflats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xflats
  template:
    metadata:
      labels:
        app: xflats
    spec:
      containers:
      - name: scraper-flats
        image: xszpo/flat_scraper:1.0.20
        env:
        - name: SCRAPER_CRAWLER_NAME
          value: 'otodom, olx, gratka'
        - name: JSONLINE_FILE_NAME
          value: 'flats_all'
        - name: GCP_FIRESTORE_COLLECTION
          value: flats
        - name: SCRAPER_CRAWL_LIST_PAGES
          value: '100'
        envFrom:
          - configMapRef:
              name: env-config
        volumeMounts:
        - name: gcpfirestore
          mountPath: "/etc/gcpfirestore"
          readOnly: true
        - name: telegram
          mountPath: "/etc/telegram"
          readOnly: true
        - name: pv-volume-scraper-storage
          mountPath: "/app/data/"
        resources:
          limits:
            cpu: "100m"
            memory: "256Mi"
      - name: scraper-plots
        image: xszpo/flat_scraper:1.0.19
        env:
        - name: SCRAPER_CRAWLER_NAME
          value: 'plot_sprzedajemy, plot_gumtree, plot_olx, plot_gratka, plot_otodom'
        - name: JSONLINE_FILE_NAME
          value: 'plots_all'
        - name: GCP_FIRESTORE_COLLECTION
          value: plots
        - name: SCRAPER_CRAWL_LIST_PAGES
          value: '2'
        envFrom:
          - configMapRef:
              name: env-config
        volumeMounts:
        - name: gcpfirestore
          mountPath: "/etc/gcpfirestore"
          readOnly: true
        - name: telegram
          mountPath: "/etc/telegram"
          readOnly: true
        - name: pv-volume-scraper-plots-storage
          mountPath: "/app/data/"
        resources:
          limits:
            cpu: "100m"
            memory: "256Mi"
      - name: luigi
        image: xszpo/flats_luigi:0.0.4
        env:
        - name: LUIGI_DAYSBACK
          value: '15'
        - name: LUIGI_BUCKET
          value: 'gs://gentle-current-314616-flats/'
        - name: LUIGI_BUCKET_PLOTS
          value: 'gs://gentle-current-314616-plots/'
        envFrom:
          - configMapRef:
              name: env-config-luigi
        volumeMounts:
        - name: gcs
          mountPath: "/etc/gcs"
          readOnly: true
        - name: gcpfirestore
          mountPath: "/etc/gcpfirestore"
          readOnly: true
        - name: telegram
          mountPath: "/etc/telegram"
          readOnly: true
        - name: pv-volume-scraper-storage
          mountPath: "/app/data/"
        - name: pv-volume-scraper-plots-storage
          mountPath: "/app/data_plots/"
        resources:
          limits:
            cpu: "100m"
            memory: "256Mi"
      - name: redis
        image: redis:5.0.8
        command:
          - redis-server
          - "/redis-master/redis.conf"
        env:
        - name: MASTER
          value: "true"
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "200m"
            memory: "512Mi"
            ephemeral-storage: "512M"
        volumeMounts:
        - name: pv-volume-redis-storage
          mountPath: /data/redis
        - name: config
          mountPath: /redis-master
      volumes:
      - name: gcpfirestore
        secret:
          secretName: gcp-firestore-6765d52h6m
      - name: gcs
        secret:
            secretName: gcp-gcs-28t8b84bgb
      - name: telegram
        secret:
            secretName: telegram-5bb96t2mf8
      - name: pv-volume-scraper-storage
        persistentVolumeClaim:
          claimName: pv-gcp-scraper-claim
      - name: pv-volume-redis-storage
        persistentVolumeClaim:
          claimName: pv-gcp-redis-claim
      - name: pv-volume-scraper-plots-storage
        persistentVolumeClaim:
          claimName: pv-gcp-scraper-plots-claim
      - name: config
        configMap:
          name: redis-config
          items:
          - key: redis.txt
            path: redis.conf