apiVersion: v1
kind: PersistentVolume
metadata:
  name: flats-json-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/xszpo/GoogleDrive/01_Projects/201907_xFlats/scraper/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flats-json-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xflats
  labels:
    app: xflats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xflats
  template:
    metadata:
      labels:
        app: xflats
    spec:
      containers:
      - name: scraper-otodom
        image: flat_scraper:1.0.0
        env:
        - name: SCRAPER_CRAWLER_NAME
          value: 'otodom'
        - name: SCRAPER_CRAWL_LIST_PAGES
          value: '1'
        - name: SCRAPER_CONCURRENT_REQUESTS
          value: '1'
        envFrom:
          - configMapRef:
              name: env-config
        volumeMounts:
        - name: gcpfirestore
          mountPath: "/etc/gcpfirestore"
          readOnly: true
        - name: flats-json-pv-storage
          mountPath: "/app/data/"
        resources:
          limits:
            cpu: "300m"
            memory: "512Mi"
            ephemeral-storage: "512M"
      - name: redis
        image: redis:buster
        ports:
          - containerPort: 6379
        resources:
          limits:
            cpu: "300m"
            memory: "512Mi"
            ephemeral-storage: "512M"
      volumes:
      - name: gcpfirestore
        secret:
          secretName: gcp-firestore-dm7t9h22dh
      - name: flats-json-pv-storage
        persistentVolumeClaim:
          claimName: flats-json-pv-claim