apiVersion: v1
kind: PersistentVolume
metadata:
  name: flats-json-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/xszpo/GoogleDrive/01_Projects/201907_xFlats/scraper/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flats-json-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi