version: "3.9"

services:

  scrapy:
    container_name: scrapy
    build:
      context: .
      dockerfile: ./Dockerfile-standalone
    volumes:
      - .:/scraper
      - ./data:/data
    env_file:
      - env-standalone.env
    networks:
      - webnet   

  redis:
    image: redis:buster
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - webnet

networks:
  webnet: